# This is the cluster secret so we can use App of Apps pattern on the ArgoCD cluster
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/#deploying-to-the-local-cluster
apiVersion: v1
kind: Secret
metadata:
  name: maul-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    name: maul
type: Opaque
stringData:
  name: maul
  server: https://maul.echobase.network:6443
