apiVersion: v1
kind: Secret
metadata:
  name: kenobi-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kenobi
  server: https://kenobi.echobase.network:6443
