apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-comfyui-proxy-service"
  namespace: comfyui
spec:
  selector:
    app: comfyui-proxy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
