apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-comfyui-nginx-config"
  namespace: comfyui
data:
  nginx.conf: |
    # load_module /usr/lib/nginx/modules/ngx_http_proxy_connect_module.so;

    # worker_process auto;

    events { }

    http {

        server {

            listen 8081;

            # ipv6=off;

            location / {
                proxy_pass http://192.168.3.6:8188;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
