#---
#apiVersion: metallb.io/v1beta1
#kind: L2Advertisement
#metadata:
#  name: l2
#  namespace: metallb-system
#spec:
#  ipAddressPools:
#    - ipv4-pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: echobase
  namespace: metallb-system
spec:
  #myASN: "{{ .Values.asn | int }}"
  myASN: 65501
  peerASN: 65500
  peerAddress: 192.168.3.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-local
  namespace: metallb-system
spec:
  ipAddressPools:
    - ipv4-pool
  aggregationLength: 25
  #aggregationLength: "{{ .Values.aggregationLength | int }}"
  localPref: 100
  communities:
    - 65535:65282
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-external
  namespace: metallb-system
spec:
  ipAddressPools:
    - ipv4-pool
  aggregationLength: 25
  #aggregationLength: "{{ .Values.aggregationLength | int }}"
  localPref: 100
  peers:
    - echobase
