# we need the CA and TOKEN variables from the remote cluster
# CA=$(kubectl get -n kube-system secret/argocd-manager-token -o jsonpath='{.data.ca\.crt}')
# TOKEN=$(kubectl get -n kube-system secret/argocd-manager-token -o jsonpath='{.data.token}' | base64 --decode)
# Apply this to the cluster hosting ArgoCD
apiVersion: v1
kind: Secret
metadata:
  name: <CLUSTER-NAME>-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    name: <CLUSER_NAME>
type: Opaque
stringData:
  name: <CLUSER_NAME>
  server: https://<CLUSTER_NAME>.echobase.network:6443
  config: |
    {
      "bearerToken": "${TOKEN}",
      "tlsClientConfig": {
        "serverName": "<CLUSER_NAME>",
        "caData": "${CA}"
      }
    }
