# we need the CA and TOKEN variables from the remote cluster
# CA=$(kubectl get -n kube-system secret/argocd-manager-token -o jsonpath='{.data.ca\.crt}')
# TOKEN=$(kubectl get -n kube-system secret/argocd-manager-token -o jsonpath='{.data.token}' | base64 --decode)
# Apply this to the cluster hosting ArgoCD
apiVersion: v1
kind: Secret
metadata:
  name: kenobi-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    name: kenobi
type: Opaque
stringData:
  name: kenobi
  server: https://kenobi.echobase.network:6443
  config: |
    {
      "bearerToken": "${TOKEN}",
      "tlsClientConfig": {
        "serverName": "kenobi",
        "caData": "${CA}"
      }
    }
