apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openwebui
resources:
  - base/openwebui-namespace.yaml
  - base/openwebui-pv.yaml
  - base/openwebui-pvc.yaml
  - base/openwebui-service.yaml
  - base/openwebui-ingress.yaml
  - base/openwebui-deploy.yaml
