apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limitrange
  namespace: monitoring
  labels:
    name: monitoring
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: 2
        memory: 1024Mi
      min:
        cpu: 250m
        memory: 256Mi
      type: Container
