apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blocky
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            name: "maul"
  template:
    metadata:
      name: blocky-{{.name}}
    spec:
      project: default
      sources:
        - repoURL: https://github.com/gattjoe/pathfinder.git
          path: blocky
          targetRevision: HEAD
          helm:
            releaseName: "{{.name}}"
        - repoURL: https://github.com/gattjoe/pathfinder.git
          path: redis
          targetRevision: HEAD
          helm:
            releaseName: blocky
            valuesObject:
              metadata:
                namespace: blocky
      destination:
        server: "{{.server}}"
        namespace: blocky
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
