apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distribution
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gattjoe/pathfinder.git
    targetRevision: 3.0.0
    chart: distribution
    helm:
      releaseName: maul
  destination:
    server: maul
    namespace: distribution
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
