apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: litellm-helm
    repoURL: https://ghcr.io/berriai/litellm-helm
    targetRevision: 0.1.812
    helm:
      releaseName: litellm-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
