apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            name: "vader"
  template:
    metadata:
      name: "metallb-{{.name}}"
    spec:
      project: default
      source:
        path: metallb
        repoURL: https://github.com/gattjoe/pathfinder
        targetRevision: HEAD
        helm:
          releaseName: "metallb-{{.name}}"
          valuesObject:
            subnet: "192.168.8.0/25"
            asn: 65501
            aggregationlength: 25
      destination:
        server: "{{.server}}"
        namespace: metallb-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
