apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
    elements:
    - cluster: maul
      url: https://kubernetes.default.svc
  template:
    metadata:
      name: prometheus-{{.cluster}}
    spec:
      project: default
      source:
        repoURL: https://github.com/gattjoe/pathfinder.git
        path: prometheus
        targetRevision: HEAD
        helm:
          releaseName: prometheus-{{.cluster}}
          valueFiles:
            - values-{{.cluster}}.yaml
      destination:
        server: "{{.url}}"
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
