apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            name: "maul"
  template:
    metadata:
      name: prometheus-{{.name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/gattjoe/pathfinder.git
        path: prometheus
        targetRevision: HEAD
        helm:
          releaseName: "{{.name}}"
          valueFiles:
            - values-{{.name}}.yaml
      destination:
        server: "{{.server}}"
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
