apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gattjoe/pathfinder.git
    path: qdrant
    targetRevision: HEAD
    helm:
      releaseName: kenobi
  destination:
    server: https://kenobi.echobase.network:6443
    namespace: qdrant-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
