apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-argoproj
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-apps
    repoURL: https://github.com/gattjoe/pathfinder
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
