apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testserver
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            name: "vader"
    - clusters:
        selector:
          matchLabels:
            name: "kenobi"
  template:
    metadata:
      name: "testserver-{{.name}}"
    spec:
      project: default
      source:
        path: testServer
        repoURL: https://github.com/gattjoe/pathfinder
        targetRevision: HEAD
        helm:
          releaseName: "{{.name}}"
          valuesObject:
            ingress:
              host: "test.echobase.network"
      destination:
        server: "{{.server}}"
        namespace: testserver
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
