apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    appendonly yes
    bind 0.0.0.0
    port 6379

    # Enable RDB saving for persistence
    save 900 1
    save 300 10
    save 60 10000

    requirepass "$(REDIS_PASSWORD)"
    USER blocky on >"$(BLOCKY_PASSWORD)" +@read +@write

    # Make secure defaults explicit
    protected-mode no
    enable-protected-configs no
    enable-debug-command no
    enable-module-command no

    dir /data
