apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-distribution-service"
  namespace: distribution
spec:
  selector:
    app: distribution
  ports:
    - port: 5000
      targetPort: 5000
      name: distribution-service
  type: LoadBalancer
  externalTrafficPolicy: Local
