apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-distribution
  namespace: distribution
  labels:
    app: distribution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distribution
  template:
    metadata:
      labels:
        app: distribution
    spec:
      containers:
        - name: distribution
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: REGISTRY_LOG_LEVEL
              value: info
          volumeMounts:
            - name: distribution-local-volume
              mountPath: /var/lib/registry
      volumes:
        - name: distribution-local-volume
          persistentVolumeClaim:
            claimName: distribution-volume-claim
