apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-local-claim
  namespace: openwebui
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      directory: openwebui
