apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-local-volume
  namespace: openwebui
  labels:
    directory: openwebui
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/openwebui
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ .Release.Name }}"
