apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-openwebui-service"
  namespace: openwebui
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: openwebui
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
