apiVersion: v1
kind: Namespace
metadata:
  name: openwebui
---
apiVersion: v1
kind: LimitRange
metadata:
  name: openwebui-limitrange
  namespace: openwebui
spec:
  limits:
    - default:
        cpu: "1"
        memory: "1024Mi"
      defaultRequest:
        cpu: "2"
        memory: "1024Mi"
      max:
        cpu: "3"
        memory: "2048Mi"
      min:
        cpu: "1"
        memory: "1024Mi"
      type: Container
