apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 9090
  type: LoadBalancer
  externalTrafficPolicy: Local
