env:
  cluster: "maul"

image:
  repository: spx01/blocky:v0.27.0@sha256:d4bb3ad54b5b3471341d11609eabb8b3d9da0faf3244da7bb2d210107b2fbc30

ingress:
  hosts: blocky.echobase.network
  host: blocky.echobase.network
