apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-qdrant-service"
  namespace: qdrant-ns
  labels:
    app.kubernetes.io/name: qdrant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
  selector:
    app: qdrant
    app.kubernetes.io/name: qdrant
