apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config-map
  namespace: qdrant-ns
data:
  initialize.sh: |
    #!/bin/sh
    echo "Soft limits"
    ulimit -a -S
    echo "Hard limits"
    ulimit -a -H
    ulimit -n $(ulimit -Hn)
    SET_INDEX=${HOSTNAME##*-}
    echo "Starting initializing for pod $SET_INDEX"
    if [ "$SET_INDEX" = "0" ]; then
      exec ./entrypoint.sh --uri 'http://qdrant.echobase.network:6335'
    else
      exec ./entrypoint.sh --bootstrap 'http://qdrant.echobase.network:6335' --uri 'http://release-name-qdrant-'"$SET_INDEX"'.release-name-qdrant-headless:6335'
    fi

  production.yaml: |
    cluster:
      consensus:
        tick_period_ms: 100
      enabled: true
    log_level: INFO
    p2p:
      enable_tls: false
      port: 6335
    service:
      # We do this on the ingress controller
      enable_tls: false
    storage:
      storage_path: ./storage
      snapshot_path: ./snapshots
      snapshots_config:
        snapshots_storage: local
      temp_path: null
    telemetry_disabled: true
