apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: qdrant-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: 6333
            - containerPort: 6334
          securityContext:
            #runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 2000
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: qdrant-local-volume
              mountPath: /qdrant/storage
            - name: qdrant-local-snapshots
              mountPath: /qdrant/snapshots
            - name: qdrant-config
              mountPath: /qdrant/config/production.yaml
              subPath: production.yaml
      volumes:
        - name: qdrant-local-volume
          persistentVolumeClaim:
            claimName: qdrant-local-claim
        - name: qdrant-local-snapshots
          persistentVolumeClaim:
            claimName: qdrant-local-snapshots-claim
        - name: qdrant-config
          configMap:
            name: qdrant-config-map
            defaultMode: 0755
