apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: testserver
spec:
  selector:
    app: nginx-testserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
