apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-testserver-ingress"
  namespace: testserver
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ .Values.ingress.hosts }}"
      secretName: testserver-prod-tls
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-testserver-service"
                port:
                  number: 80
