apiVersion: v1
kind: Namespace
metadata:
  name: testserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-testserver"
  namespace: testserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-testserver
  template:
    metadata:
      labels:
        app: nginx-testserver
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}"
          volumeMounts:
            - name: custom-homepage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: custom-homepage
          configMap:
            name: "{{ .Release.Name }}-cm"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-cm"
  namespace: testserver
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Release.Name }}</title>
      <body>{{ .Release.Name }}</body>
    </head>
    </html>
