apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: distribution-volume-claim
  namespace: distribution
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      directory: registry
