apiVersion: v1
kind: ConfigMap
metadata:
  name: distribution-cm
  namespace: distribution
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: false
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
      tag:
        concurrencylimit: 8
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/registry
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      host: https://registry.echobase.network:5000
