apiVersion: v1
kind: PersistentVolume
metadata:
  name: distribution-local-volume
  namespace: distribution
  labels:
    directory: registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: In
              values:
                - "true"
