apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  prometheus.io/port: "10254"
  prometheus.io/scrape: "true"
  prometheus.io/scheme: "http"
  prometheus.io/path: "/metrics"
