spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: controller
          args:
            - "--enable-metrics=true"
          ports:
            - name: prometheus
              containerPort: 10254
