apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/gattjoe/pathfinder.git"
  destinations:
    - server: "https://192.168.3.2:6443"
      namespace: "*"
    - server: "https://kenobi.echobase.network:6443"
      namespace: "*"
    - server: "https://kubernetes.default.svc"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
