apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
  - base/cert-manager-prod.yaml
