apiVersion: v1
kind: PersistentVolume
metadata:
  name: blocky-local-volume
  namespace: blocky
  labels:
    directory: blocky
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/blocky
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ .Values.env.cluster }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blocky-local-claim
  namespace: blocky
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      directory: blocky
