apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-blocky-service"
  namespace: blocky
spec:
  selector:
    app: blocky
  ports:
    - port: 4000
      targetPort: 4000
      name: blocky-admin-http
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  type: LoadBalancer
  externalTrafficPolicy: Local
