apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limitrange
  namespace: blocky
spec:
  limits:
    - default:
        memory: 1000Mi
      defaultRequest:
        memory: 1000Mi
      type: Container
