apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-blocky-cm"
  namespace: blocky
data:
  config.yml: |
    upstreams:
      init:
        strategy: blocking
      groups:
        # OpenDNS for now
        default:
          - 208.67.222.222:53
          - 208.67.220.220:53
      strategy: parallel_best
      timeout: 2s

    connectIPVersion: v4

    clientLookup:
      clients:
        andym1:
          - 192.168.4.131
        andyiphone:
          - 192.168.4.145
        applewatch:
          - 192.168.4.239
        cope:
          - 192.168.4.200
        francescaapplewatch:
          - 192.168.4.103
        francescanewipad:
          - 192.168.4.105
        class0:
          - 192.168.4.117
        mrblack:
          - 192.168.4.241
        ninoapplewatch:
          - 192.168.4.138
        ninoipad:
          - 192.168.4.158
        samsunggalaxyx:
          - 192.168.4.211

        # IOT
        familyroomnest:
          - 192.168.2.228
        lutron:
          - 192.168.4.204
        nestprotect:
          - 192.168.2.164
        peloton:
          - 192.168.2.59
        upstairsnest:
          - 192.168.2.139
        rachio:
          - 192.168.2.81

        # TV
        familyroomappletv:
          - 192.168.4.44
        gymappletv:
          - 192.168.4.78
        gymtv:
          - 192.168.2.70
        officeappletv:
          - 192.168.4.93
        porchtv:
          - 192.168.2.150
        upstairsappletv:
          - 192.168.4.151

        # Game consoles
        nintendoswitch:
          - 192.168.2.36
        xbox:
          - 192.168.2.20

        # Alexa
        enzoechodot:
          - 192.168.2.114
        ninoechodot:
          - 192.168.2.38
        kitchenecho:
          - 192.168.2.51
        francescaecho:
          - 192.168.2.165

        # Chromebook
        francescachromebook:
          - 192.168.2.106
        ninochromebook:
          - 192.168.2.195

    blocking:
      blockType: zeroIP

      loading:
        refreshPeriod: 4h
        downloads:
          timeout: 1m
          attempts: 5
          cooldown: 10s
        maxErrorsPerSource: 10
        concurrency: 5

      denylists:
        ads:
          - https://adaway.org/hosts.txt
          - https://v.firebog.net/hosts/Easyprivacy.txt
          - https://v.firebog.net/hosts/Prigent-Ads.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        malware:
          - https://urlhaus.abuse.ch/downloads/hostfile/
          - https://phishing.army/download/phishing_army_blocklist_extended.txt

      allowlists:
        ads:
          - |
            aa.online-metrix.net
            disney.demdex.net
            analytics.disneyplus.com
            saa.paramountplus.com
            conviva.com
            email.accounts.playmetrics.com
            tags.tiqcdn.com
            cbsinteractive.data.adobedc.net
            int.vaicore.site
            paramountplus.com.data.adobedc.net
            track.canva.com
            pagead2.googlesyndication.com
            pubads.g.doubleclick.net
            click.messages.psncenergy.com
            email.pmsends.com
            learn.cisecurity.org
            click.discord.com
            links.h6.hilton.com
            get.venmo.com

      clientGroupsBlock:
        default:
          - ads
          - malware
        andym1:
          - malware
        andyiphone:
          - malware

    prometheus:
      enable: true

    ports:
      dns: 53
      http: 4000

    queryLog:
      # optional one of: mysql, postgresql, timescale, csv
      type: csv
      # directory for csv, db connection string for postgresql
      target: /dnsLogs

      logRetentionDays: 365
      creationAttempts: 1
      creationCooldown: 2s
      # optional: Which fields should be logged. You can choose one or more from: clientIP, clientName, responseReason, responseAnswer, question, duration. If not defined, it logs all fields
      fields:
        - clientIP
        - clientName
        - question
        - responseReason
        - responseAnswer
        - duration
      flushInterval: 30s

    redis:
      address: redis.echobase.network:6379
      username: blocky
      connectionAttempts: 10
      connectionCooldown: 3s
